---
fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    pulp: "#{source_dir}"
  forge_modules:
    extlib:
      repo: puppet-extlib
      ref: 1.1.0
    apache:
      repo: puppetlabs-apache
      ref: 1.11.1
    concat:
      repo: puppetlabs-concat
      ref: 2.2.1
    mongodb:
      repo: puppetlabs-mongodb
      ref: 0.17.0
    qpid:
      repo: katello-qpid
      ref: 2.2.0
    squid3:
      repo: thias-squid3
      ref: 1.0.2
